# Generated by Django 6.0.3 on 2026-03-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ai_api_key',
            field=models.CharField(blank=True, help_text='Your AI provider API key. Stored in plaintext — use a dedicated key.', max_length=200),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ai_provider',
            field=models.CharField(choices=[('anthropic', 'Anthropic (Claude)'), ('openai', 'OpenAI (GPT)')], default='anthropic', max_length=20),
        ),
    ]
