# Generated by Django 6.0.3 on 2026-03-25 17:52

import contents.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='content_files/%Y/%m/', validators=[contents.validators.validate_file_extension, contents.validators.validate_file_size]),
        ),
        migrations.AddField(
            model_name='content',
            name='preview_image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
